# Generated by Django 4.2.1 on 2023-11-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='work_status',
            field=models.IntegerField(choices=[(1, 'Готово к изготовлению'), (2, 'Изготовление ресурса'), (3, 'На тех. обслуживании')], default=1, verbose_name='Статус станка'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_title', models.CharField(max_length=250, verbose_name='Название ресурса')),
                ('making_status', models.IntegerField(choices=[(1, 'В процессе изготовления'), (2, 'Изготовлен'), (3, 'Изготовление отменено')], default=1, verbose_name='Статус ресурса')),
                ('external_resource_id', models.IntegerField(verbose_name='Идентификатор ресурса из микросервиса')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='machine.machine')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
    ]
