# Generated by Django 4.2.1 on 2023-11-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_work_status_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='port_baudrate',
            field=models.IntegerField(choices=[(50, '50'), (75, '75'), (110, '110'), (134, '134'), (150, '150'), (200, '200'), (300, '300'), (600, '600'), (1200, '1200'), (1800, '1800'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (19200, '19200'), (38400, '38400'), (57600, '57600'), (115200, '115200'), (230400, '230400'), (460800, '460800'), (500000, '500000'), (576000, '576000'), (921600, '921600'), (1000000, '1000000'), (1152000, '1152000'), (1500000, '1500000'), (2000000, '2000000'), (2500000, '2500000'), (3000000, '3000000'), (3500000, '3500000'), (4000000, '4000000')], default=115200, verbose_name='Битрейт порта'),
        ),
        migrations.AddField(
            model_name='machine',
            name='port_read_timeout',
            field=models.FloatField(default=1, verbose_name='Таймаут на чтение из порта'),
        ),
        migrations.AddField(
            model_name='machine',
            name='port_write_timeout',
            field=models.FloatField(default=1, verbose_name='Таймаут на запись в порт'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='work_status',
            field=models.IntegerField(choices=[(1, 'Готов к работе'), (2, 'Занят'), (3, 'На тех. обслуживании')], default=1, verbose_name='Статус станка'),
        ),
    ]
